### ISSUE TITLE
 'mathjax-node' error while running transform_mathjax()

### ISSUE THREAD

**Issue by durraniu** [ardata-fr/equatags#1]
I understand that this package is quite new. But it looked so interesting that I tried it out. Based on the following error, I think I need to install node.js? 

Kindly have a look, and thank you for this and other great packages that you have authored.  

## Reproducible Example
I ran the code from the readme and got the following error: 
```
> library(equatags)
> x <- c("(ax^2 + bx + c = 0)",
+        "x = {-b \\pm \\sqrt{b^2-4ac} \\over 2a}")
> z <- transform_mathjax(x = x, to = "svg")
Error in transform_mathjax(x = x, to = "svg") : 
  'mathjax-node' is not in your user data directory, run `install_mathjax_npm()` to install it
> install_mathjax_npm()
Error in install_mathjax_npm() : 
  'node-js' is not available or cannot be found.
```

**Comment by davidgohel** [comment]
yes

I have updated the error message so that it is clearer.
