### ISSUE TITLE
texPreview

### ISSUE THREAD

**Issue by yonicd** [ardata-fr/equatags#3]
This is a similar idea as [texPreview](https://github.com/yonicd/texpreview). Maybe it can be useful for you as you develop.

**Comment by davidgohel** [comment]
Sorry if it's a duplicate (but I am not sure if it is). I was not aware of your package. The idea is to provide an extension to flextable for equations.

I need to have an SVG and OOML export for flextable https://github.com/davidgohel/flextable/tree/equatags

**Comment by davidgohel** [comment]
I added a note, could you review it and tell me if it is ok? Feel free to add additional information.

https://github.com/davidgohel/equatags#related-work

Your work may be useful for flextable as I don't have any preview for latex output. 

Were you thinking about something specific about equatags and your package?

**Comment by yonicd** [comment]
No worries. Lots of packages out there. The note looks good, thanks. 

I have been using flextable more lately since moving jobs and needing office more than pdfs of late.

I haven't really used mathjax as images yet, because I could always use latex for it. But the new flexibility would be nice.

**Comment by yonicd** [comment]
for extending texpreview for flextable latex it should be simple. the underlying mechanism is S3 so you can add the class and the class specific function to get to latex from flextable and texpreview should be able to take it from there.

there are many examples here: https://github.com/yonicd/texPreview/blob/master/R/tex_preview.R
