### ISSUE TITLE
Version 0.2.1 on CRAN?

### ISSUE THREAD

**Issue by phgrosjean** [ardata-fr/equatags#5]
Hi @davidgohel. Would it be possible to update {equatags} on CRAN to version 0.2.1? I badly need changes mades between v0.2.0 and 0.2.1 and thus, I have to add a Remotes entry in the DESCRIPTION file of my package until v0.2.1 will be on CRAN.

Thanks!

**Comment by davidgohel** [comment]
Hi @phgrosjean, sure, I will give a try this afternoon, it should be straightforward

**Comment by davidgohel** [comment]
It went OK :)
